In [13]:
import numpy as np

x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [17]:
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
np.hstack((a, b))

a = ([1], [2], [3])
b = ([4], [5], [6])
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])